FROM node:lts-bullseye as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ENV REACT_APP_MAIL_SERVER_URL=https://ssedgzjhal.execute-api.us-east-1.amazonaws.com

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD npm start
